name: story_arc
description: A premium, AI-first journaling application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  cloud_firestore: any
  firebase_core: any
  firebase_auth: any
  firebase_analytics: any
  firebase_crashlytics: any
  flutter_secure_storage: any
  google_fonts: ^5.1.0
  flutter_animate: any
  go_router: any
  path_provider: any
  intl: any
  emoji_picker_flutter: any
  record: any
  just_audio: any
  web_socket_channel: any
  uuid: any
  flutter_pcm_sound: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
